//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace EWShop.LoginWebserviceMWG {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginWebserviceMWG.LoginSvcSoap")]
    public interface LoginSvcSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        EWShop.LoginWebserviceMWG.LoginResponse Login(EWShop.LoginWebserviceMWG.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.LoginWebserviceMWG.LoginResponse> LoginAsync(EWShop.LoginWebserviceMWG.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoPOS", ReplyAction="*")]
        EWShop.LoginWebserviceMWG.GetInfoPOSResponse GetInfoPOS(EWShop.LoginWebserviceMWG.GetInfoPOSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoPOS", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.LoginWebserviceMWG.GetInfoPOSResponse> GetInfoPOSAsync(EWShop.LoginWebserviceMWG.GetInfoPOSRequest request);
        LoginResponse Login(LoginRequestBody request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.LoginWebserviceMWG.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(EWShop.LoginWebserviceMWG.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMessageError;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string strUserName, string strPassword, string strMessageError) {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
            this.strMessageError = strMessageError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.LoginWebserviceMWG.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(EWShop.LoginWebserviceMWG.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strMessageError;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult, string strMessageError) {
            this.LoginResult = LoginResult;
            this.strMessageError = strMessageError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoPOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoPOS", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.LoginWebserviceMWG.GetInfoPOSRequestBody Body;
        
        public GetInfoPOSRequest() {
        }
        
        public GetInfoPOSRequest(EWShop.LoginWebserviceMWG.GetInfoPOSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInfoPOSRequestBody {
        
        public GetInfoPOSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoPOSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoPOSResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.LoginWebserviceMWG.GetInfoPOSResponseBody Body;
        
        public GetInfoPOSResponse() {
        }
        
        public GetInfoPOSResponse(EWShop.LoginWebserviceMWG.GetInfoPOSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoPOSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetInfoPOSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strConfig;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMessageError;
        
        public GetInfoPOSResponseBody() {
        }
        
        public GetInfoPOSResponseBody(bool GetInfoPOSResult, string strConfig, string strMessageError) {
            this.GetInfoPOSResult = GetInfoPOSResult;
            this.strConfig = strConfig;
            this.strMessageError = strMessageError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSvcSoapChannel : EWShop.LoginWebserviceMWG.LoginSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSvcSoapClient : System.ServiceModel.ClientBase<EWShop.LoginWebserviceMWG.LoginSvcSoap>, LoginSvcSoap {
        
        public LoginSvcSoapClient() {
        }
        
        public LoginSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.LoginWebserviceMWG.LoginResponse EWShop.LoginWebserviceMWG.LoginSvcSoap.Login(EWShop.LoginWebserviceMWG.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string strUserName, string strPassword, ref string strMessageError) {
            EWShop.LoginWebserviceMWG.LoginRequest inValue = new EWShop.LoginWebserviceMWG.LoginRequest();
            inValue.Body = new EWShop.LoginWebserviceMWG.LoginRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strMessageError = strMessageError;
            EWShop.LoginWebserviceMWG.LoginResponse retVal = ((EWShop.LoginWebserviceMWG.LoginSvcSoap)(this)).Login(inValue);
            strMessageError = retVal.Body.strMessageError;
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.LoginWebserviceMWG.LoginResponse> EWShop.LoginWebserviceMWG.LoginSvcSoap.LoginAsync(EWShop.LoginWebserviceMWG.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.LoginWebserviceMWG.LoginResponse> LoginAsync(string strUserName, string strPassword, string strMessageError) {
            EWShop.LoginWebserviceMWG.LoginRequest inValue = new EWShop.LoginWebserviceMWG.LoginRequest();
            inValue.Body = new EWShop.LoginWebserviceMWG.LoginRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            inValue.Body.strMessageError = strMessageError;
            return ((EWShop.LoginWebserviceMWG.LoginSvcSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.LoginWebserviceMWG.GetInfoPOSResponse EWShop.LoginWebserviceMWG.LoginSvcSoap.GetInfoPOS(EWShop.LoginWebserviceMWG.GetInfoPOSRequest request) {
            return base.Channel.GetInfoPOS(request);
        }
        
        public bool GetInfoPOS(out string strConfig, out string strMessageError) {
            EWShop.LoginWebserviceMWG.GetInfoPOSRequest inValue = new EWShop.LoginWebserviceMWG.GetInfoPOSRequest();
            inValue.Body = new EWShop.LoginWebserviceMWG.GetInfoPOSRequestBody();
            EWShop.LoginWebserviceMWG.GetInfoPOSResponse retVal = ((EWShop.LoginWebserviceMWG.LoginSvcSoap)(this)).GetInfoPOS(inValue);
            strConfig = retVal.Body.strConfig;
            strMessageError = retVal.Body.strMessageError;
            return retVal.Body.GetInfoPOSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.LoginWebserviceMWG.GetInfoPOSResponse> EWShop.LoginWebserviceMWG.LoginSvcSoap.GetInfoPOSAsync(EWShop.LoginWebserviceMWG.GetInfoPOSRequest request) {
            return base.Channel.GetInfoPOSAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.LoginWebserviceMWG.GetInfoPOSResponse> GetInfoPOSAsync() {
            EWShop.LoginWebserviceMWG.GetInfoPOSRequest inValue = new EWShop.LoginWebserviceMWG.GetInfoPOSRequest();
            inValue.Body = new EWShop.LoginWebserviceMWG.GetInfoPOSRequestBody();
            return ((EWShop.LoginWebserviceMWG.LoginSvcSoap)(this)).GetInfoPOSAsync(inValue);
        }

        public LoginResponse Login(LoginRequestBody request)
        {
            throw new NotImplementedException();
        }
    }
}
