//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWShop.InterfaceServerRequest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://haier.com", ConfigurationName="InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService")]
    public interface SPI_spcAEV_spcCCM_spcInterface_spcService {
        
        // CODEGEN: Generating message contract since the operation CheckSrStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://haier.com:CheckSrStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EWShop.InterfaceServerRequest.CheckSrStatusResponse CheckSrStatus(EWShop.InterfaceServerRequest.CheckSrStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://haier.com:CheckSrStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.CheckSrStatusResponse> CheckSrStatusAsync(EWShop.InterfaceServerRequest.CheckSrStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation InsertProdReg is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://haier.com:InsertProdReg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EWShop.InterfaceServerRequest.InsertProdRegResponse InsertProdReg(EWShop.InterfaceServerRequest.InsertProdRegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://haier.com:InsertProdReg", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.InsertProdRegResponse> InsertProdRegAsync(EWShop.InterfaceServerRequest.InsertProdRegRequest request);
        
        // CODEGEN: Generating message contract since the operation Request is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="document/http://haier.com:Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EWShop.InterfaceServerRequest.RequestResponse Request(EWShop.InterfaceServerRequest.RequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="document/http://haier.com:Request", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.RequestResponse> RequestAsync(EWShop.InterfaceServerRequest.RequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://haier.com")]
    public partial class CheckSrStatus_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string sHOPCODEField;
        
        private string sRNumField;
        
        private string requestDateToField;
        
        private string homePhoneField;
        
        private string requestCodeField;
        
        private string requestDateFromField;
        
        private string workPhoneField;
        
        private string sourceTypeField;
        
        private string sourceCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SHOPCODE {
            get {
                return this.sHOPCODEField;
            }
            set {
                this.sHOPCODEField = value;
                this.RaisePropertyChanged("SHOPCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SRNum {
            get {
                return this.sRNumField;
            }
            set {
                this.sRNumField = value;
                this.RaisePropertyChanged("SRNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestDateTo {
            get {
                return this.requestDateToField;
            }
            set {
                this.requestDateToField = value;
                this.RaisePropertyChanged("RequestDateTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("HomePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RequestCode {
            get {
                return this.requestCodeField;
            }
            set {
                this.requestCodeField = value;
                this.RaisePropertyChanged("RequestCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RequestDateFrom {
            get {
                return this.requestDateFromField;
            }
            set {
                this.requestDateFromField = value;
                this.RaisePropertyChanged("RequestDateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
                this.RaisePropertyChanged("WorkPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("SourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SourceCode {
            get {
                return this.sourceCodeField;
            }
            set {
                this.sourceCodeField = value;
                this.RaisePropertyChanged("SourceCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SPIRightNowInboundObject")]
    public partial class ServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string emailAddressField;
        
        private string mobilePhoneField;
        
        private string homePhoneField;
        
        private string detailAddressField;
        
        private string categoryField;
        
        private string descriptionField;
        
        private string serialNumField;
        
        private string countryField;
        
        private string purchaseDateField;
        
        private string productModelField;
        
        private string sourceTypeField;
        
        private string sourceCodeField;
        
        private string shopContactField;
        
        private string brandField;
        
        private string requestCodeField;
        
        private string addressIdField;
        
        private string stateField;
        
        private string cityField;
        
        private string streetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("MobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("HomePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DetailAddress {
            get {
                return this.detailAddressField;
            }
            set {
                this.detailAddressField = value;
                this.RaisePropertyChanged("DetailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SerialNum {
            get {
                return this.serialNumField;
            }
            set {
                this.serialNumField = value;
                this.RaisePropertyChanged("SerialNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PurchaseDate {
            get {
                return this.purchaseDateField;
            }
            set {
                this.purchaseDateField = value;
                this.RaisePropertyChanged("PurchaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ProductModel {
            get {
                return this.productModelField;
            }
            set {
                this.productModelField = value;
                this.RaisePropertyChanged("ProductModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("SourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SourceCode {
            get {
                return this.sourceCodeField;
            }
            set {
                this.sourceCodeField = value;
                this.RaisePropertyChanged("SourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ShopContact {
            get {
                return this.shopContactField;
            }
            set {
                this.shopContactField = value;
                this.RaisePropertyChanged("ShopContact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("Brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string RequestCode {
            get {
                return this.requestCodeField;
            }
            set {
                this.requestCodeField = value;
                this.RaisePropertyChanged("RequestCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AddressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
                this.RaisePropertyChanged("AddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SPIRightNowInboundObject")]
    public partial class ProductRegister : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string countryField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string genderField;
        
        private string customerTypeField;
        
        private string telPhoneField;
        
        private string mobilePhoneField;
        
        private string officePhoneField;
        
        private string ageField;
        
        private string birthdayField;
        
        private string emailField;
        
        private string faxField;
        
        private string brandField;
        
        private string categoryField;
        
        private string productModelField;
        
        private string serialNumField;
        
        private string purchaseDateField;
        
        private string expiryDateField;
        
        private string expiredDateField;
        
        private string statusField;
        
        private string haveYouPurchasedExtendedWarrantyField;
        
        private string retailerNameField;
        
        private string retailerAddressField;
        
        private string retailerPostcodeField;
        
        private string retailerCityField;
        
        private string retailerContactFirstNameField;
        
        private string retailerContactLastNameField;
        
        private string retailerContactPhoneField;
        
        private string retailerEmailField;
        
        private string addressField;
        
        private string addressIdField;
        
        private string cityField;
        
        private string stateField;
        
        private string streetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string customerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
                this.RaisePropertyChanged("customerType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string telPhone {
            get {
                return this.telPhoneField;
            }
            set {
                this.telPhoneField = value;
                this.RaisePropertyChanged("telPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string mobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("mobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string officePhone {
            get {
                return this.officePhoneField;
            }
            set {
                this.officePhoneField = value;
                this.RaisePropertyChanged("officePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string productModel {
            get {
                return this.productModelField;
            }
            set {
                this.productModelField = value;
                this.RaisePropertyChanged("productModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string serialNum {
            get {
                return this.serialNumField;
            }
            set {
                this.serialNumField = value;
                this.RaisePropertyChanged("serialNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string purchaseDate {
            get {
                return this.purchaseDateField;
            }
            set {
                this.purchaseDateField = value;
                this.RaisePropertyChanged("purchaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string expiredDate {
            get {
                return this.expiredDateField;
            }
            set {
                this.expiredDateField = value;
                this.RaisePropertyChanged("expiredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string haveYouPurchasedExtendedWarranty {
            get {
                return this.haveYouPurchasedExtendedWarrantyField;
            }
            set {
                this.haveYouPurchasedExtendedWarrantyField = value;
                this.RaisePropertyChanged("haveYouPurchasedExtendedWarranty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string retailerName {
            get {
                return this.retailerNameField;
            }
            set {
                this.retailerNameField = value;
                this.RaisePropertyChanged("retailerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string retailerAddress {
            get {
                return this.retailerAddressField;
            }
            set {
                this.retailerAddressField = value;
                this.RaisePropertyChanged("retailerAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string retailerPostcode {
            get {
                return this.retailerPostcodeField;
            }
            set {
                this.retailerPostcodeField = value;
                this.RaisePropertyChanged("retailerPostcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string retailerCity {
            get {
                return this.retailerCityField;
            }
            set {
                this.retailerCityField = value;
                this.RaisePropertyChanged("retailerCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string retailerContactFirstName {
            get {
                return this.retailerContactFirstNameField;
            }
            set {
                this.retailerContactFirstNameField = value;
                this.RaisePropertyChanged("retailerContactFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string retailerContactLastName {
            get {
                return this.retailerContactLastNameField;
            }
            set {
                this.retailerContactLastNameField = value;
                this.RaisePropertyChanged("retailerContactLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string retailerContactPhone {
            get {
                return this.retailerContactPhoneField;
            }
            set {
                this.retailerContactPhoneField = value;
                this.RaisePropertyChanged("retailerContactPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string retailerEmail {
            get {
                return this.retailerEmailField;
            }
            set {
                this.retailerEmailField = value;
                this.RaisePropertyChanged("retailerEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string AddressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
                this.RaisePropertyChanged("AddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SPIRightNowInboundObject")]
    public partial class Repair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string changedNoField;
        
        private string changedStatusField;
        
        private string statusChangeDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ChangedNo {
            get {
                return this.changedNoField;
            }
            set {
                this.changedNoField = value;
                this.RaisePropertyChanged("ChangedNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChangedStatus {
            get {
                return this.changedStatusField;
            }
            set {
                this.changedStatusField = value;
                this.RaisePropertyChanged("ChangedStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusChangeDate {
            get {
                return this.statusChangeDateField;
            }
            set {
                this.statusChangeDateField = value;
                this.RaisePropertyChanged("StatusChangeDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SPIRightNowInboundObject")]
    public partial class serviceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerNameField;
        
        private string customerDetailAddressField;
        
        private Repair[] listOfRepairField;
        
        private string customerPhoneField;
        
        private string brandField;
        
        private string categoryField;
        
        private string productModelField;
        
        private string dateField;
        
        private string statusField;
        
        private string aSPNameField;
        
        private string remarksField;
        
        private string serialNumberField;
        
        private string dOPField;
        
        private string l3Field;
        
        private string sRNumField;
        
        private string serviceClassField;
        
        private string partNmuberField;
        
        private string orderDateField;
        
        private string shipDateField;
        
        private string receiveDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerDetailAddress {
            get {
                return this.customerDetailAddressField;
            }
            set {
                this.customerDetailAddressField = value;
                this.RaisePropertyChanged("CustomerDetailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Repair[] ListOfRepair {
            get {
                return this.listOfRepairField;
            }
            set {
                this.listOfRepairField = value;
                this.RaisePropertyChanged("ListOfRepair");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustomerPhone {
            get {
                return this.customerPhoneField;
            }
            set {
                this.customerPhoneField = value;
                this.RaisePropertyChanged("CustomerPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("Brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ProductModel {
            get {
                return this.productModelField;
            }
            set {
                this.productModelField = value;
                this.RaisePropertyChanged("ProductModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ASPName {
            get {
                return this.aSPNameField;
            }
            set {
                this.aSPNameField = value;
                this.RaisePropertyChanged("ASPName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("Remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("serialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DOP {
            get {
                return this.dOPField;
            }
            set {
                this.dOPField = value;
                this.RaisePropertyChanged("DOP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string L3 {
            get {
                return this.l3Field;
            }
            set {
                this.l3Field = value;
                this.RaisePropertyChanged("L3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SRNum {
            get {
                return this.sRNumField;
            }
            set {
                this.sRNumField = value;
                this.RaisePropertyChanged("SRNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ServiceClass {
            get {
                return this.serviceClassField;
            }
            set {
                this.serviceClassField = value;
                this.RaisePropertyChanged("ServiceClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PartNmuber {
            get {
                return this.partNmuberField;
            }
            set {
                this.partNmuberField = value;
                this.RaisePropertyChanged("PartNmuber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
                this.RaisePropertyChanged("OrderDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
                this.RaisePropertyChanged("ShipDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ReceiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
                this.RaisePropertyChanged("ReceiveDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://haier.com")]
    public partial class CheckSrStatus_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private serviceRequest[] listOfserviceRequestField;
        
        private string requestDateFromField;
        
        private string requestDateToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.siebel.com/xml/SPIRightNowInboundObject", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public serviceRequest[] ListOfserviceRequest {
            get {
                return this.listOfserviceRequestField;
            }
            set {
                this.listOfserviceRequestField = value;
                this.RaisePropertyChanged("ListOfserviceRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string requestDateFrom {
            get {
                return this.requestDateFromField;
            }
            set {
                this.requestDateFromField = value;
                this.RaisePropertyChanged("requestDateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string requestDateTo {
            get {
                return this.requestDateToField;
            }
            set {
                this.requestDateToField = value;
                this.RaisePropertyChanged("requestDateTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSrStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://haier.com", Order=0)]
        public EWShop.InterfaceServerRequest.CheckSrStatus_Input CheckSrStatus_Input;
        
        public CheckSrStatusRequest() {
        }
        
        public CheckSrStatusRequest(EWShop.InterfaceServerRequest.CheckSrStatus_Input CheckSrStatus_Input) {
            this.CheckSrStatus_Input = CheckSrStatus_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSrStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://haier.com", Order=0)]
        public EWShop.InterfaceServerRequest.CheckSrStatus_Output CheckSrStatus_Output;
        
        public CheckSrStatusResponse() {
        }
        
        public CheckSrStatusResponse(EWShop.InterfaceServerRequest.CheckSrStatus_Output CheckSrStatus_Output) {
            this.CheckSrStatus_Output = CheckSrStatus_Output;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://haier.com")]
    public partial class InsertProdReg_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductRegister productRegisterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.siebel.com/xml/SPIRightNowInboundObject", Order=0)]
        public ProductRegister ProductRegister {
            get {
                return this.productRegisterField;
            }
            set {
                this.productRegisterField = value;
                this.RaisePropertyChanged("ProductRegister");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://haier.com")]
    public partial class InsertProdReg_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProdRegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://haier.com", Order=0)]
        public EWShop.InterfaceServerRequest.InsertProdReg_Input InsertProdReg_Input;
        
        public InsertProdRegRequest() {
        }
        
        public InsertProdRegRequest(EWShop.InterfaceServerRequest.InsertProdReg_Input InsertProdReg_Input) {
            this.InsertProdReg_Input = InsertProdReg_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertProdRegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://haier.com", Order=0)]
        public EWShop.InterfaceServerRequest.InsertProdReg_Output InsertProdReg_Output;
        
        public InsertProdRegResponse() {
        }
        
        public InsertProdRegResponse(EWShop.InterfaceServerRequest.InsertProdReg_Output InsertProdReg_Output) {
            this.InsertProdReg_Output = InsertProdReg_Output;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://haier.com")]
    public partial class Request_Input : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceRequest serviceRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.siebel.com/xml/SPIRightNowInboundObject", Order=0)]
        public ServiceRequest ServiceRequest {
            get {
                return this.serviceRequestField;
            }
            set {
                this.serviceRequestField = value;
                this.RaisePropertyChanged("ServiceRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://haier.com")]
    public partial class Request_Output : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string error_spcCodeField;
        
        private string error_spcMessageField;
        
        private string requestCodeField;
        
        private string sRNumField;
        
        private string sourceCodeField;
        
        private string sourceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Error_spcCode {
            get {
                return this.error_spcCodeField;
            }
            set {
                this.error_spcCodeField = value;
                this.RaisePropertyChanged("Error_spcCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error_spcMessage {
            get {
                return this.error_spcMessageField;
            }
            set {
                this.error_spcMessageField = value;
                this.RaisePropertyChanged("Error_spcMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestCode {
            get {
                return this.requestCodeField;
            }
            set {
                this.requestCodeField = value;
                this.RaisePropertyChanged("RequestCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SRNum {
            get {
                return this.sRNumField;
            }
            set {
                this.sRNumField = value;
                this.RaisePropertyChanged("SRNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SourceCode {
            get {
                return this.sourceCodeField;
            }
            set {
                this.sourceCodeField = value;
                this.RaisePropertyChanged("SourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("SourceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://haier.com", Order=0)]
        public EWShop.InterfaceServerRequest.Request_Input Request_Input;
        
        public RequestRequest() {
        }
        
        public RequestRequest(EWShop.InterfaceServerRequest.Request_Input Request_Input) {
            this.Request_Input = Request_Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://haier.com", Order=0)]
        public EWShop.InterfaceServerRequest.Request_Output Request_Output;
        
        public RequestResponse() {
        }
        
        public RequestResponse(EWShop.InterfaceServerRequest.Request_Output Request_Output) {
            this.Request_Output = Request_Output;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SPI_spcAEV_spcCCM_spcInterface_spcServiceChannel : EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPI_spcAEV_spcCCM_spcInterface_spcServiceClient : System.ServiceModel.ClientBase<EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService>, EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService {
        
        public SPI_spcAEV_spcCCM_spcInterface_spcServiceClient() {
        }
        
        public SPI_spcAEV_spcCCM_spcInterface_spcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPI_spcAEV_spcCCM_spcInterface_spcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPI_spcAEV_spcCCM_spcInterface_spcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPI_spcAEV_spcCCM_spcInterface_spcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.InterfaceServerRequest.CheckSrStatusResponse EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService.CheckSrStatus(EWShop.InterfaceServerRequest.CheckSrStatusRequest request) {
            return base.Channel.CheckSrStatus(request);
        }
        
        public EWShop.InterfaceServerRequest.CheckSrStatus_Output CheckSrStatus(EWShop.InterfaceServerRequest.CheckSrStatus_Input CheckSrStatus_Input) {
            EWShop.InterfaceServerRequest.CheckSrStatusRequest inValue = new EWShop.InterfaceServerRequest.CheckSrStatusRequest();
            inValue.CheckSrStatus_Input = CheckSrStatus_Input;
            EWShop.InterfaceServerRequest.CheckSrStatusResponse retVal = ((EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService)(this)).CheckSrStatus(inValue);
            return retVal.CheckSrStatus_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.CheckSrStatusResponse> EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService.CheckSrStatusAsync(EWShop.InterfaceServerRequest.CheckSrStatusRequest request) {
            return base.Channel.CheckSrStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.CheckSrStatusResponse> CheckSrStatusAsync(EWShop.InterfaceServerRequest.CheckSrStatus_Input CheckSrStatus_Input) {
            EWShop.InterfaceServerRequest.CheckSrStatusRequest inValue = new EWShop.InterfaceServerRequest.CheckSrStatusRequest();
            inValue.CheckSrStatus_Input = CheckSrStatus_Input;
            return ((EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService)(this)).CheckSrStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.InterfaceServerRequest.InsertProdRegResponse EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService.InsertProdReg(EWShop.InterfaceServerRequest.InsertProdRegRequest request) {
            return base.Channel.InsertProdReg(request);
        }
        
        public EWShop.InterfaceServerRequest.InsertProdReg_Output InsertProdReg(EWShop.InterfaceServerRequest.InsertProdReg_Input InsertProdReg_Input) {
            EWShop.InterfaceServerRequest.InsertProdRegRequest inValue = new EWShop.InterfaceServerRequest.InsertProdRegRequest();
            inValue.InsertProdReg_Input = InsertProdReg_Input;
            EWShop.InterfaceServerRequest.InsertProdRegResponse retVal = ((EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService)(this)).InsertProdReg(inValue);
            return retVal.InsertProdReg_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.InsertProdRegResponse> EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService.InsertProdRegAsync(EWShop.InterfaceServerRequest.InsertProdRegRequest request) {
            return base.Channel.InsertProdRegAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.InsertProdRegResponse> InsertProdRegAsync(EWShop.InterfaceServerRequest.InsertProdReg_Input InsertProdReg_Input) {
            EWShop.InterfaceServerRequest.InsertProdRegRequest inValue = new EWShop.InterfaceServerRequest.InsertProdRegRequest();
            inValue.InsertProdReg_Input = InsertProdReg_Input;
            return ((EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService)(this)).InsertProdRegAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.InterfaceServerRequest.RequestResponse EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService.Request(EWShop.InterfaceServerRequest.RequestRequest request) {
            return base.Channel.Request(request);
        }
        
        public EWShop.InterfaceServerRequest.Request_Output Request(EWShop.InterfaceServerRequest.Request_Input Request_Input) {
            EWShop.InterfaceServerRequest.RequestRequest inValue = new EWShop.InterfaceServerRequest.RequestRequest();
            inValue.Request_Input = Request_Input;
            EWShop.InterfaceServerRequest.RequestResponse retVal = ((EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService)(this)).Request(inValue);
            return retVal.Request_Output;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.RequestResponse> EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService.RequestAsync(EWShop.InterfaceServerRequest.RequestRequest request) {
            return base.Channel.RequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.InterfaceServerRequest.RequestResponse> RequestAsync(EWShop.InterfaceServerRequest.Request_Input Request_Input) {
            EWShop.InterfaceServerRequest.RequestRequest inValue = new EWShop.InterfaceServerRequest.RequestRequest();
            inValue.Request_Input = Request_Input;
            return ((EWShop.InterfaceServerRequest.SPI_spcAEV_spcCCM_spcInterface_spcService)(this)).RequestAsync(inValue);
        }
    }
}
