//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWShop.ExecuteWebserviceMWG {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POAcknowledgement", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class POAcknowledgement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoldCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCodeField;
        
        private System.DateTime OrderDateField;
        
        private System.DateTime InputDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EWShop.ExecuteWebserviceMWG.Message MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EWShop.ExecuteWebserviceMWG.Item[] ItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SoldCode {
            get {
                return this.SoldCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SoldCodeField, value) != true)) {
                    this.SoldCodeField = value;
                    this.RaisePropertyChanged("SoldCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ShipCode {
            get {
                return this.ShipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCodeField, value) != true)) {
                    this.ShipCodeField = value;
                    this.RaisePropertyChanged("ShipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime InputDate {
            get {
                return this.InputDateField;
            }
            set {
                if ((this.InputDateField.Equals(value) != true)) {
                    this.InputDateField = value;
                    this.RaisePropertyChanged("InputDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public EWShop.ExecuteWebserviceMWG.Message Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public EWShop.ExecuteWebserviceMWG.Item[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        private decimal QuantityField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EWShop.ExecuteWebserviceMWG.Message MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string QuantityUnit {
            get {
                return this.QuantityUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityUnitField, value) != true)) {
                    this.QuantityUnitField = value;
                    this.RaisePropertyChanged("QuantityUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public EWShop.ExecuteWebserviceMWG.Message Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Quotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        private System.Nullable<decimal> SalePriceField;
        
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        private int PriceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> SalePrice {
            get {
                return this.SalePriceField;
            }
            set {
                if ((this.SalePriceField.Equals(value) != true)) {
                    this.SalePriceField = value;
                    this.RaisePropertyChanged("SalePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int PriceType {
            get {
                return this.PriceTypeField;
            }
            set {
                if ((this.PriceTypeField.Equals(value) != true)) {
                    this.PriceTypeField = value;
                    this.RaisePropertyChanged("PriceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Stock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        private decimal StockQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExecuteWebserviceMWG.AquaSvcSoap")]
    public interface AquaSvcSoap {
        
        // CODEGEN: Generating message contract since element name strAuthen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecutePOAcknowledgement", ReplyAction="*")]
        EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponse ExecutePOAcknowledgement(EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecutePOAcknowledgement", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponse> ExecutePOAcknowledgementAsync(EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest request);
        
        // CODEGEN: Generating message contract since element name strAuthen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteQuotation", ReplyAction="*")]
        EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponse ExecuteQuotation(EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteQuotation", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponse> ExecuteQuotationAsync(EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest request);
        
        // CODEGEN: Generating message contract since element name strAuthen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteStock", ReplyAction="*")]
        EWShop.ExecuteWebserviceMWG.ExecuteStockResponse ExecuteStock(EWShop.ExecuteWebserviceMWG.ExecuteStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecuteStock", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecuteStockResponse> ExecuteStockAsync(EWShop.ExecuteWebserviceMWG.ExecuteStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecutePOAcknowledgementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecutePOAcknowledgement", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequestBody Body;
        
        public ExecutePOAcknowledgementRequest() {
        }
        
        public ExecutePOAcknowledgementRequest(EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecutePOAcknowledgementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strAuthen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EWShop.ExecuteWebserviceMWG.POAcknowledgement objPOA;
        
        public ExecutePOAcknowledgementRequestBody() {
        }
        
        public ExecutePOAcknowledgementRequestBody(string strAuthen, EWShop.ExecuteWebserviceMWG.POAcknowledgement objPOA) {
            this.strAuthen = strAuthen;
            this.objPOA = objPOA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecutePOAcknowledgementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecutePOAcknowledgementResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponseBody Body;
        
        public ExecutePOAcknowledgementResponse() {
        }
        
        public ExecutePOAcknowledgementResponse(EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecutePOAcknowledgementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EWShop.ExecuteWebserviceMWG.ResponseMessage ExecutePOAcknowledgementResult;
        
        public ExecutePOAcknowledgementResponseBody() {
        }
        
        public ExecutePOAcknowledgementResponseBody(EWShop.ExecuteWebserviceMWG.ResponseMessage ExecutePOAcknowledgementResult) {
            this.ExecutePOAcknowledgementResult = ExecutePOAcknowledgementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteQuotationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteQuotation", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequestBody Body;
        
        public ExecuteQuotationRequest() {
        }
        
        public ExecuteQuotationRequest(EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteQuotationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strAuthen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EWShop.ExecuteWebserviceMWG.Quotation[] objQuotations;
        
        public ExecuteQuotationRequestBody() {
        }
        
        public ExecuteQuotationRequestBody(string strAuthen, EWShop.ExecuteWebserviceMWG.Quotation[] objQuotations) {
            this.strAuthen = strAuthen;
            this.objQuotations = objQuotations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteQuotationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteQuotationResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponseBody Body;
        
        public ExecuteQuotationResponse() {
        }
        
        public ExecuteQuotationResponse(EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteQuotationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EWShop.ExecuteWebserviceMWG.ResponseMessage ExecuteQuotationResult;
        
        public ExecuteQuotationResponseBody() {
        }
        
        public ExecuteQuotationResponseBody(EWShop.ExecuteWebserviceMWG.ResponseMessage ExecuteQuotationResult) {
            this.ExecuteQuotationResult = ExecuteQuotationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteStock", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.ExecuteWebserviceMWG.ExecuteStockRequestBody Body;
        
        public ExecuteStockRequest() {
        }
        
        public ExecuteStockRequest(EWShop.ExecuteWebserviceMWG.ExecuteStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strAuthen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EWShop.ExecuteWebserviceMWG.Stock[] objStocks;
        
        public ExecuteStockRequestBody() {
        }
        
        public ExecuteStockRequestBody(string strAuthen, EWShop.ExecuteWebserviceMWG.Stock[] objStocks) {
            this.strAuthen = strAuthen;
            this.objStocks = objStocks;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.ExecuteWebserviceMWG.ExecuteStockResponseBody Body;
        
        public ExecuteStockResponse() {
        }
        
        public ExecuteStockResponse(EWShop.ExecuteWebserviceMWG.ExecuteStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EWShop.ExecuteWebserviceMWG.ResponseMessage ExecuteStockResult;
        
        public ExecuteStockResponseBody() {
        }
        
        public ExecuteStockResponseBody(EWShop.ExecuteWebserviceMWG.ResponseMessage ExecuteStockResult) {
            this.ExecuteStockResult = ExecuteStockResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AquaSvcSoapChannel : EWShop.ExecuteWebserviceMWG.AquaSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AquaSvcSoapClient : System.ServiceModel.ClientBase<EWShop.ExecuteWebserviceMWG.AquaSvcSoap>, EWShop.ExecuteWebserviceMWG.AquaSvcSoap {
        
        public AquaSvcSoapClient() {
        }
        
        public AquaSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AquaSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AquaSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AquaSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponse EWShop.ExecuteWebserviceMWG.AquaSvcSoap.ExecutePOAcknowledgement(EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest request) {
            return base.Channel.ExecutePOAcknowledgement(request);
        }
        
        public EWShop.ExecuteWebserviceMWG.ResponseMessage ExecutePOAcknowledgement(string strAuthen, EWShop.ExecuteWebserviceMWG.POAcknowledgement objPOA) {
            EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest inValue = new EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest();
            inValue.Body = new EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequestBody();
            inValue.Body.strAuthen = strAuthen;
            inValue.Body.objPOA = objPOA;
            EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponse retVal = ((EWShop.ExecuteWebserviceMWG.AquaSvcSoap)(this)).ExecutePOAcknowledgement(inValue);
            return retVal.Body.ExecutePOAcknowledgementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponse> EWShop.ExecuteWebserviceMWG.AquaSvcSoap.ExecutePOAcknowledgementAsync(EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest request) {
            return base.Channel.ExecutePOAcknowledgementAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementResponse> ExecutePOAcknowledgementAsync(string strAuthen, EWShop.ExecuteWebserviceMWG.POAcknowledgement objPOA) {
            EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest inValue = new EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequest();
            inValue.Body = new EWShop.ExecuteWebserviceMWG.ExecutePOAcknowledgementRequestBody();
            inValue.Body.strAuthen = strAuthen;
            inValue.Body.objPOA = objPOA;
            return ((EWShop.ExecuteWebserviceMWG.AquaSvcSoap)(this)).ExecutePOAcknowledgementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponse EWShop.ExecuteWebserviceMWG.AquaSvcSoap.ExecuteQuotation(EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest request) {
            return base.Channel.ExecuteQuotation(request);
        }
        
        public EWShop.ExecuteWebserviceMWG.ResponseMessage ExecuteQuotation(string strAuthen, EWShop.ExecuteWebserviceMWG.Quotation[] objQuotations) {
            EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest inValue = new EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest();
            inValue.Body = new EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequestBody();
            inValue.Body.strAuthen = strAuthen;
            inValue.Body.objQuotations = objQuotations;
            EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponse retVal = ((EWShop.ExecuteWebserviceMWG.AquaSvcSoap)(this)).ExecuteQuotation(inValue);
            return retVal.Body.ExecuteQuotationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponse> EWShop.ExecuteWebserviceMWG.AquaSvcSoap.ExecuteQuotationAsync(EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest request) {
            return base.Channel.ExecuteQuotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecuteQuotationResponse> ExecuteQuotationAsync(string strAuthen, EWShop.ExecuteWebserviceMWG.Quotation[] objQuotations) {
            EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest inValue = new EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequest();
            inValue.Body = new EWShop.ExecuteWebserviceMWG.ExecuteQuotationRequestBody();
            inValue.Body.strAuthen = strAuthen;
            inValue.Body.objQuotations = objQuotations;
            return ((EWShop.ExecuteWebserviceMWG.AquaSvcSoap)(this)).ExecuteQuotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.ExecuteWebserviceMWG.ExecuteStockResponse EWShop.ExecuteWebserviceMWG.AquaSvcSoap.ExecuteStock(EWShop.ExecuteWebserviceMWG.ExecuteStockRequest request) {
            return base.Channel.ExecuteStock(request);
        }
        
        public EWShop.ExecuteWebserviceMWG.ResponseMessage ExecuteStock(string strAuthen, EWShop.ExecuteWebserviceMWG.Stock[] objStocks) {
            EWShop.ExecuteWebserviceMWG.ExecuteStockRequest inValue = new EWShop.ExecuteWebserviceMWG.ExecuteStockRequest();
            inValue.Body = new EWShop.ExecuteWebserviceMWG.ExecuteStockRequestBody();
            inValue.Body.strAuthen = strAuthen;
            inValue.Body.objStocks = objStocks;
            EWShop.ExecuteWebserviceMWG.ExecuteStockResponse retVal = ((EWShop.ExecuteWebserviceMWG.AquaSvcSoap)(this)).ExecuteStock(inValue);
            return retVal.Body.ExecuteStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecuteStockResponse> EWShop.ExecuteWebserviceMWG.AquaSvcSoap.ExecuteStockAsync(EWShop.ExecuteWebserviceMWG.ExecuteStockRequest request) {
            return base.Channel.ExecuteStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.ExecuteWebserviceMWG.ExecuteStockResponse> ExecuteStockAsync(string strAuthen, EWShop.ExecuteWebserviceMWG.Stock[] objStocks) {
            EWShop.ExecuteWebserviceMWG.ExecuteStockRequest inValue = new EWShop.ExecuteWebserviceMWG.ExecuteStockRequest();
            inValue.Body = new EWShop.ExecuteWebserviceMWG.ExecuteStockRequestBody();
            inValue.Body.strAuthen = strAuthen;
            inValue.Body.objStocks = objStocks;
            return ((EWShop.ExecuteWebserviceMWG.AquaSvcSoap)(this)).ExecuteStockAsync(inValue);
        }
    }
}
