//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWShop.FiboReceiver {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FiboReceiver.MtReceiverSoap")]
    public interface MtReceiverSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMt", ReplyAction="*")]
        EWShop.FiboReceiver.ReceiveMtResponse ReceiveMt(EWShop.FiboReceiver.ReceiveMtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMt", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtResponse> ReceiveMtAsync(EWShop.FiboReceiver.ReceiveMtRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMtCSKH", ReplyAction="*")]
        EWShop.FiboReceiver.ReceiveMtCSKHResponse ReceiveMtCSKH(EWShop.FiboReceiver.ReceiveMtCSKHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMtCSKH", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtCSKHResponse> ReceiveMtCSKHAsync(EWShop.FiboReceiver.ReceiveMtCSKHRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMtQC", ReplyAction="*")]
        EWShop.FiboReceiver.ReceiveMtQCResponse ReceiveMtQC(EWShop.FiboReceiver.ReceiveMtQCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMtQC", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtQCResponse> ReceiveMtQCAsync(EWShop.FiboReceiver.ReceiveMtQCRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMtReplyMo", ReplyAction="*")]
        EWShop.FiboReceiver.ReceiveMtReplyMoResponse ReceiveMtReplyMo(EWShop.FiboReceiver.ReceiveMtReplyMoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMtReplyMo", ReplyAction="*")]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtReplyMoResponse> ReceiveMtReplyMoAsync(EWShop.FiboReceiver.ReceiveMtReplyMoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMt", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtRequestBody Body;
        
        public ReceiveMtRequest() {
        }
        
        public ReceiveMtRequest(EWShop.FiboReceiver.ReceiveMtRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrefixId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CommandCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int MoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public byte MtTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RequestId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MsgContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public byte MsgContentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public byte FeeTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int CampaignId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OtherInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public byte IsSchedule;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ScheduleTime;
        
        public ReceiveMtRequestBody() {
        }
        
        public ReceiveMtRequestBody(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, int MoId, byte MtTypeId, string RequestId, string MsgContent, byte MsgContentTypeId, byte FeeTypeId, int CampaignId, string OtherInfo, byte IsSchedule, string ScheduleTime) {
            this.Username = Username;
            this.Password = Password;
            this.PhoneNumber = PhoneNumber;
            this.PrefixId = PrefixId;
            this.CommandCode = CommandCode;
            this.MoId = MoId;
            this.MtTypeId = MtTypeId;
            this.RequestId = RequestId;
            this.MsgContent = MsgContent;
            this.MsgContentTypeId = MsgContentTypeId;
            this.FeeTypeId = FeeTypeId;
            this.CampaignId = CampaignId;
            this.OtherInfo = OtherInfo;
            this.IsSchedule = IsSchedule;
            this.ScheduleTime = ScheduleTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMtResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtResponseBody Body;
        
        public ReceiveMtResponse() {
        }
        
        public ReceiveMtResponse(EWShop.FiboReceiver.ReceiveMtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte ReceiveMtResult;
        
        public ReceiveMtResponseBody() {
        }
        
        public ReceiveMtResponseBody(byte ReceiveMtResult) {
            this.ReceiveMtResult = ReceiveMtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtCSKHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMtCSKH", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtCSKHRequestBody Body;
        
        public ReceiveMtCSKHRequest() {
        }
        
        public ReceiveMtCSKHRequest(EWShop.FiboReceiver.ReceiveMtCSKHRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtCSKHRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrefixId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CommandCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RequestId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MsgContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public byte MsgContentTypeId;
        
        public ReceiveMtCSKHRequestBody() {
        }
        
        public ReceiveMtCSKHRequestBody(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, string RequestId, string MsgContent, byte MsgContentTypeId) {
            this.Username = Username;
            this.Password = Password;
            this.PhoneNumber = PhoneNumber;
            this.PrefixId = PrefixId;
            this.CommandCode = CommandCode;
            this.RequestId = RequestId;
            this.MsgContent = MsgContent;
            this.MsgContentTypeId = MsgContentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtCSKHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMtCSKHResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtCSKHResponseBody Body;
        
        public ReceiveMtCSKHResponse() {
        }
        
        public ReceiveMtCSKHResponse(EWShop.FiboReceiver.ReceiveMtCSKHResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtCSKHResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte ReceiveMtCSKHResult;
        
        public ReceiveMtCSKHResponseBody() {
        }
        
        public ReceiveMtCSKHResponseBody(byte ReceiveMtCSKHResult) {
            this.ReceiveMtCSKHResult = ReceiveMtCSKHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtQCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMtQC", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtQCRequestBody Body;
        
        public ReceiveMtQCRequest() {
        }
        
        public ReceiveMtQCRequest(EWShop.FiboReceiver.ReceiveMtQCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtQCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrefixId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CommandCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RequestId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MsgContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public byte MsgContentTypeId;
        
        public ReceiveMtQCRequestBody() {
        }
        
        public ReceiveMtQCRequestBody(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, string RequestId, string MsgContent, byte MsgContentTypeId) {
            this.Username = Username;
            this.Password = Password;
            this.PhoneNumber = PhoneNumber;
            this.PrefixId = PrefixId;
            this.CommandCode = CommandCode;
            this.RequestId = RequestId;
            this.MsgContent = MsgContent;
            this.MsgContentTypeId = MsgContentTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtQCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMtQCResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtQCResponseBody Body;
        
        public ReceiveMtQCResponse() {
        }
        
        public ReceiveMtQCResponse(EWShop.FiboReceiver.ReceiveMtQCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtQCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte ReceiveMtQCResult;
        
        public ReceiveMtQCResponseBody() {
        }
        
        public ReceiveMtQCResponseBody(byte ReceiveMtQCResult) {
            this.ReceiveMtQCResult = ReceiveMtQCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtReplyMoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMtReplyMo", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtReplyMoRequestBody Body;
        
        public ReceiveMtReplyMoRequest() {
        }
        
        public ReceiveMtReplyMoRequest(EWShop.FiboReceiver.ReceiveMtReplyMoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtReplyMoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrefixId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CommandCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int MoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RequestId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MsgContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public byte MsgContentTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public byte FeeTypeId;
        
        public ReceiveMtReplyMoRequestBody() {
        }
        
        public ReceiveMtReplyMoRequestBody(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, int MoId, string RequestId, string MsgContent, byte MsgContentTypeId, byte FeeTypeId) {
            this.Username = Username;
            this.Password = Password;
            this.PhoneNumber = PhoneNumber;
            this.PrefixId = PrefixId;
            this.CommandCode = CommandCode;
            this.MoId = MoId;
            this.RequestId = RequestId;
            this.MsgContent = MsgContent;
            this.MsgContentTypeId = MsgContentTypeId;
            this.FeeTypeId = FeeTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMtReplyMoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMtReplyMoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EWShop.FiboReceiver.ReceiveMtReplyMoResponseBody Body;
        
        public ReceiveMtReplyMoResponse() {
        }
        
        public ReceiveMtReplyMoResponse(EWShop.FiboReceiver.ReceiveMtReplyMoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMtReplyMoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte ReceiveMtReplyMoResult;
        
        public ReceiveMtReplyMoResponseBody() {
        }
        
        public ReceiveMtReplyMoResponseBody(byte ReceiveMtReplyMoResult) {
            this.ReceiveMtReplyMoResult = ReceiveMtReplyMoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MtReceiverSoapChannel : EWShop.FiboReceiver.MtReceiverSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MtReceiverSoapClient : System.ServiceModel.ClientBase<EWShop.FiboReceiver.MtReceiverSoap>, EWShop.FiboReceiver.MtReceiverSoap {
        
        public MtReceiverSoapClient() {
        }
        
        public MtReceiverSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MtReceiverSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MtReceiverSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MtReceiverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.FiboReceiver.ReceiveMtResponse EWShop.FiboReceiver.MtReceiverSoap.ReceiveMt(EWShop.FiboReceiver.ReceiveMtRequest request) {
            return base.Channel.ReceiveMt(request);
        }
        
        public byte ReceiveMt(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, int MoId, byte MtTypeId, string RequestId, string MsgContent, byte MsgContentTypeId, byte FeeTypeId, int CampaignId, string OtherInfo, byte IsSchedule, string ScheduleTime) {
            EWShop.FiboReceiver.ReceiveMtRequest inValue = new EWShop.FiboReceiver.ReceiveMtRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.MoId = MoId;
            inValue.Body.MtTypeId = MtTypeId;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            inValue.Body.FeeTypeId = FeeTypeId;
            inValue.Body.CampaignId = CampaignId;
            inValue.Body.OtherInfo = OtherInfo;
            inValue.Body.IsSchedule = IsSchedule;
            inValue.Body.ScheduleTime = ScheduleTime;
            EWShop.FiboReceiver.ReceiveMtResponse retVal = ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMt(inValue);
            return retVal.Body.ReceiveMtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtResponse> EWShop.FiboReceiver.MtReceiverSoap.ReceiveMtAsync(EWShop.FiboReceiver.ReceiveMtRequest request) {
            return base.Channel.ReceiveMtAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtResponse> ReceiveMtAsync(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, int MoId, byte MtTypeId, string RequestId, string MsgContent, byte MsgContentTypeId, byte FeeTypeId, int CampaignId, string OtherInfo, byte IsSchedule, string ScheduleTime) {
            EWShop.FiboReceiver.ReceiveMtRequest inValue = new EWShop.FiboReceiver.ReceiveMtRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.MoId = MoId;
            inValue.Body.MtTypeId = MtTypeId;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            inValue.Body.FeeTypeId = FeeTypeId;
            inValue.Body.CampaignId = CampaignId;
            inValue.Body.OtherInfo = OtherInfo;
            inValue.Body.IsSchedule = IsSchedule;
            inValue.Body.ScheduleTime = ScheduleTime;
            return ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.FiboReceiver.ReceiveMtCSKHResponse EWShop.FiboReceiver.MtReceiverSoap.ReceiveMtCSKH(EWShop.FiboReceiver.ReceiveMtCSKHRequest request) {
            return base.Channel.ReceiveMtCSKH(request);
        }
        
        public byte ReceiveMtCSKH(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, string RequestId, string MsgContent, byte MsgContentTypeId) {
            EWShop.FiboReceiver.ReceiveMtCSKHRequest inValue = new EWShop.FiboReceiver.ReceiveMtCSKHRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtCSKHRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            EWShop.FiboReceiver.ReceiveMtCSKHResponse retVal = ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMtCSKH(inValue);
            return retVal.Body.ReceiveMtCSKHResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtCSKHResponse> EWShop.FiboReceiver.MtReceiverSoap.ReceiveMtCSKHAsync(EWShop.FiboReceiver.ReceiveMtCSKHRequest request) {
            return base.Channel.ReceiveMtCSKHAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtCSKHResponse> ReceiveMtCSKHAsync(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, string RequestId, string MsgContent, byte MsgContentTypeId) {
            EWShop.FiboReceiver.ReceiveMtCSKHRequest inValue = new EWShop.FiboReceiver.ReceiveMtCSKHRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtCSKHRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            return ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMtCSKHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.FiboReceiver.ReceiveMtQCResponse EWShop.FiboReceiver.MtReceiverSoap.ReceiveMtQC(EWShop.FiboReceiver.ReceiveMtQCRequest request) {
            return base.Channel.ReceiveMtQC(request);
        }
        
        public byte ReceiveMtQC(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, string RequestId, string MsgContent, byte MsgContentTypeId) {
            EWShop.FiboReceiver.ReceiveMtQCRequest inValue = new EWShop.FiboReceiver.ReceiveMtQCRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtQCRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            EWShop.FiboReceiver.ReceiveMtQCResponse retVal = ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMtQC(inValue);
            return retVal.Body.ReceiveMtQCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtQCResponse> EWShop.FiboReceiver.MtReceiverSoap.ReceiveMtQCAsync(EWShop.FiboReceiver.ReceiveMtQCRequest request) {
            return base.Channel.ReceiveMtQCAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtQCResponse> ReceiveMtQCAsync(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, string RequestId, string MsgContent, byte MsgContentTypeId) {
            EWShop.FiboReceiver.ReceiveMtQCRequest inValue = new EWShop.FiboReceiver.ReceiveMtQCRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtQCRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            return ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMtQCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EWShop.FiboReceiver.ReceiveMtReplyMoResponse EWShop.FiboReceiver.MtReceiverSoap.ReceiveMtReplyMo(EWShop.FiboReceiver.ReceiveMtReplyMoRequest request) {
            return base.Channel.ReceiveMtReplyMo(request);
        }
        
        public byte ReceiveMtReplyMo(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, int MoId, string RequestId, string MsgContent, byte MsgContentTypeId, byte FeeTypeId) {
            EWShop.FiboReceiver.ReceiveMtReplyMoRequest inValue = new EWShop.FiboReceiver.ReceiveMtReplyMoRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtReplyMoRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.MoId = MoId;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            inValue.Body.FeeTypeId = FeeTypeId;
            EWShop.FiboReceiver.ReceiveMtReplyMoResponse retVal = ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMtReplyMo(inValue);
            return retVal.Body.ReceiveMtReplyMoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtReplyMoResponse> EWShop.FiboReceiver.MtReceiverSoap.ReceiveMtReplyMoAsync(EWShop.FiboReceiver.ReceiveMtReplyMoRequest request) {
            return base.Channel.ReceiveMtReplyMoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EWShop.FiboReceiver.ReceiveMtReplyMoResponse> ReceiveMtReplyMoAsync(string Username, string Password, string PhoneNumber, string PrefixId, string CommandCode, int MoId, string RequestId, string MsgContent, byte MsgContentTypeId, byte FeeTypeId) {
            EWShop.FiboReceiver.ReceiveMtReplyMoRequest inValue = new EWShop.FiboReceiver.ReceiveMtReplyMoRequest();
            inValue.Body = new EWShop.FiboReceiver.ReceiveMtReplyMoRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.PhoneNumber = PhoneNumber;
            inValue.Body.PrefixId = PrefixId;
            inValue.Body.CommandCode = CommandCode;
            inValue.Body.MoId = MoId;
            inValue.Body.RequestId = RequestId;
            inValue.Body.MsgContent = MsgContent;
            inValue.Body.MsgContentTypeId = MsgContentTypeId;
            inValue.Body.FeeTypeId = FeeTypeId;
            return ((EWShop.FiboReceiver.MtReceiverSoap)(this)).ReceiveMtReplyMoAsync(inValue);
        }
    }
}
